services:
  - type: web
    name: paperpilot-ai
    env: python
    pythonVersion: 3.11.10
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: ELSEVIER_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
