services:
  - type: web
    name: paperpilot-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: ELSEVIER_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: demo@paperpilot.com
      - key: SMTP_PASS
        value: demo_password_123
      - key: SMTP_SECURE
        value: false
    healthCheckPath: /health
    autoDeploy: true
    plan: starter